# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdf9727353c5c821b77f818a92bf2de924ab2ccdcee83432e489f234e9dd4b52a79486905607362c60978ea513899241590df2f407537c234cfdf7f7128e8908

test:
  secret_key_base: 273469366e4ed6fa32b5c3ba2f33a2263f3d3dbd41b672e825020d85f7e0b42bc75911468d1cf1c593c811322b089934d7c815ed0e4d89a4793294e3fbdc5b4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
